### ISSUE TITLE
Issue when refreshing

### ISSUE THREAD

**Issue by jennycao-arcurve** [wmartins/react-blur-up#1]
When I am refreshing the browser, the image onLoad event is not fired in my code. I think it is because the original placeLoader is in the cache. But your code seems working fine. Do you have any idea why mine is not working :)?

Thanks!

Best,
Jenny

**Comment by wmartins** [comment]
Hey @jennycao-arcurve, what browser/browser version are you using?

About the issue itself, what's happening? You reload the page and the "big" image isn't loading?

Also, how big (the size in KBs/MBs) is your image?

Thanks!

**Comment by jennycao-arcurve** [comment]
Thank you for your reply! 

I am using the latest version of Chrome.

When I refresh, after the render method of blur up component, it did not call the onLoadPlaceholder() and just end the process. I checked online. It seems that since my browser has cache of the Placeholder image, it will not load again.

And when I use develop tool, it shows that only the small image is in the <span className="blur-up__hidden"></span>. And there is no children in <div className={`blur-up__aspect-ratio blur-up__aspect-ratio--${ratio}`}></div>.

I have tried your london1 image with url from github. not working :(.

**Comment by jennycao-arcurve** [comment]
I have to use styled components in my project :(
Thank you!

import React from 'react';
import styled from 'styled-components';

const Hidden = styled.span`
  position: absolute;
  left: -999em;
`;

const Wrapper = styled.div`
  position: relative;
  overflow: hidden;
  padding-bottom: 75%;
`;

const ImageStyle = styled.div`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;

  width: 100%;
  height: 100%;

  background-position: 50% 50%;
  background-size: cover;
`;

const PlaceHolderStyle = styled.div`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;

  width: 100%;
  height: 100%;

  background-position: 50% 50%;
  background-size: cover;

  filter: blur(15px);

  transition: all .3s ease;
  transition-property: opacity, visibility;

  visibility: visible;
  opacity: 1;
`;

const PlaceHolderFadeOutStyle = styled.div`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;

  width: 100%;
  height: 100%;

  background-position: 50% 50%;
  background-size: cover;

  filter: blur(15px);

  transition: all .3s ease;
  transition-property: opacity, visibility;

  visibility: hidden;
  opacity: 0;
`;

class BlurUp extends React.Component {
  constructor(props) {
    super(props);

    this.onLoadPlaceholder = this.onLoadPlaceholder.bind(this);
    this.onLoadImage = this.onLoadImage.bind(this);

    this.state = {};
  }

  onLoadPlaceholder() {
    this.setState({
      isPlaceholderLoaded: true,
    });
  }

  onLoadImage() {
    this.setState({
      isImageLoaded: true,
    });
  }

  render() {
    const { url, placeholderURL } = this.props;
    const { isPlaceholderLoaded, isImageLoaded } = this.state;

    const pHpart = isImageLoaded ?
      (<PlaceHolderFadeOutStyle>
        <img src={placeholderURL} alt="test"/>
      </PlaceHolderFadeOutStyle>)
      : (<PlaceHolderStyle>
        <img src={placeholderURL} alt="test"/>
      </PlaceHolderStyle>);
    //   (<PlaceHolderFadeOutStyle style={{ backgroundImage: `url(${placeholderURL})` }} />)
    //   : <PlaceHolderStyle style={{ backgroundImage: `url(${placeholderURL})` }} />;

    const placeholderImageContainer = isPlaceholderLoaded ? pHpart : null;

    const image = isPlaceholderLoaded ? <img src={url} onLoad={this.onLoadImage} alt="s" /> : null;

    const imageContainer = isImageLoaded ?
      (<ImageStyle>
        <img src={url} alt="s"/>
      </ImageStyle>) : null;

    return (
      <div>
        <Hidden>
          <img src={this.props.placeholderURL} onLoad={this.onLoadPlaceholder} alt="presentation" />
          {image}
        </Hidden>
        <Wrapper>
          {imageContainer}
          {placeholderImageContainer}
        </Wrapper>
        {this.props.children}
      </div>
    );
  }
}

export default BlurUp;

**Comment by wmartins** [comment]
I think you're correct about the cache, what do you think about trying something like this:

http://mikefowler.me/journal/2014/04/22/cached-images-load-event

Basically, you will check if the image download has been completed, then, you'll fire up the `load` event.

It's strange that it's working on my example. 😄

Lets see if we can figure it out.

**Comment by jennycao-arcurve** [comment]
Got it working. Thanks! :)

**Comment by wmartins** [comment]
Nice @jennycao-arcurve!

**Comment by wmartins** [comment]
@jennycao-arcurve, do you mind if we close this issue?

**Comment by jennycao-arcurve** [comment]
No problem! Thanks!
